name: Live Stream Pro
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # يعيد تشغيل نفسه كل 6 ساعات

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
      
      - name: Start Streaming
        run: |
          ffmpeg -re -i "https://rtmp.alkafeel.net:8081/live/stream/playlist.m3u8" \
          -c:v libx264 -preset ultrafast -tune zerolatency -b:v 1500k \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/q12g-s6wc-0y03-0ua5-6e6p"
